---
name: nginx-site-scams-encyapps-com
services:
  fake-encyapps:
    image: nginx:latest
    container_name: site-scams-encyapps-com

    restart: always

    ports:
      - '${PORT}:80'

    volumes:
      - ../appdata/site-scams-fake-links:/usr/share/nginx/html:ro

    networks:
      - frontend
      - web-servers

#----------------------------------------------------------

networks:
  frontend:
    external: true
  web-servers:
    external: true